config/routes.rb
Rails.application.routes.draw do
  
  resources :site_contents
  resources :categories
  resources :orders do 
    resources:orderitems
  end

  
  
  
  devise_for :users do 
    resources :orders 
  end
  
  get 'dynamicpage/:location' => 'static_pages#dynamicPage'
  
  
  post '/search' => 'items#search'
  get 'category/:title' => 'static_pages#category'
  
 # get 'cart/index'

  resources :items
  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'
  
  
  get '/login' => 'user#login'
  
    get '/logout' => 'user#logout'
    
    
    get '/checkout' => 'cart#createOrder' 
    
    
    # This looks like what we did for the add item ...... Muuhhhhh yes Liam you are right......
    
    
get '/remove/:id' => 'cart#remove'


get '/reduce/:id' => 'cart#reduce'


get '/cart/clearcart' => 'cart#clearcart'

get '/cart' => 'cart#index'

get '/cart/:id' => 'cart#add'

get '/upgrade/:id' => 'static_pages#upgrade'
get '/downgrade/:id' => 'static_pages#downgrade'

get '/allusers' => 'static_pages#allusers'


 get '/paid/:id' => 'static_pages#paid' 




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   # current_user.update_attribute :admin, true
   
   @categories = Category.all
   
   
  end
  
  
  def category
    catName = params[:title]
    @items = Item.where("category like ? ", catName)
  end

  
  def dynamicPage
   catName = params[:location]
    @site_contents = SiteContent.where("location like ? ", catName)
  end
  

  def help
 

    
  end

  def about
       @user = User.find_by(id: params[:id])
    @user.update_attribute(:admin, true)
    redirect_to "/"
  end
  
  
  def allusers
   
    @users = User.all
  end
  
  
  
   
   def paid
    # redirect_to "/cart/clear"
    flash[:notice] = 'Transaction Complete'
       @order = Order.find_by(id: params[:id])
    @order.update_attribute(:status , "Paid by User: #{current_user.email}")
    #"Paid by User:#{current_user.id} #{current_user.name} #{current_user.surname}")
    
   end

   
  
  
  
   def upgrade 
    @user = User.find_by(id: params[:id])
    @user.update_attribute(:admin, true)
    redirect_to "/"
  end
  
   def downgrade 
    @user = User.find_by(id: params[:id])
    @user.update_attribute(:admin, false)
    redirect_to "/"
  end
  
  
  
  
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/allusers.html.erb
<h1>Heool here are all the users</h1>





<div class="mainCont">
    
    <h1>All The People...... So Many People....</h1>
    
    
    
    <% if user_signed_in? && current_user.admin? %>
<% @users.each do |user| %>


    <div class="itemhols">
    
   <h1>User Id: <%= user.id %></h1>
   <h1>email: <%= user.email %></h1>
   <h1>Admin: <%= user.admin %></h1>
    <p><a href="/upgrade/<%= user.id %>" class="button">Make Admin</a></p>
    <p><a href="/downgrade/<%= user.id %>" class="button">Make Not Admin</a></p>
    </div>
   
<% end %>
    
    <% end %>
    
    
    
</div>

app/views/static_pages/category.html.erb
<p id="notice"><%= notice %></p>

<% if @items.length == 0  %>
<br />
<h2>There are currently no products in this category</h2>
<% end %>




<div id="itemsContainer">
<h1>Items</h1>
    <% @items.each do |item| %>
      <div class="itemhols">
        <h1><%= item.title %></h1>
        <%= link_to (image_tag item.image_url, :class=>"itemholsIm"), item %>
       <p><%= item.description %>
       </p>
       <p><%= item.price %>
        <br>
        <%= item.category %>
        <br>
        <%= item.brand %>
        </p>
        <p>        
         
          <a href="/cart/<%= item.id %>" class="button">Add to Cart</a>  
          <%= link_to 'Show', item, :class =>"button", :role=>"button" %>
        

        <% if session[:login] == 1 %> 
        <%= link_to 'Edit', edit_item_path(item), :class =>"button", :role=>"button" %>
        <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button",           :role=>"button" %>
        
        <% end %>
        </p>
     </div>
    <% end %>
  <br>

app/views/static_pages/dynamicPage.html.erb
<p id="notice"><%= notice %></p>

<h1>Site Contents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Heading1</th>
      <th>Heading2</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_contents.each do |site_content| %>
      <tr>
        <td><%= site_content.title %></td>
        <td><%= site_content.heading1 %></td>
        <td><%= site_content.heading2 %></td>
        <td><%= site_content.location %></td>
        <td><%= link_to 'Show', site_content %></td>
        <td><%= link_to 'Edit', edit_site_content_path(site_content) %></td>
        <td><%= link_to 'Destroy', site_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site Content', new_site_content_path %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

<%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button"  %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>


<div class="mainCont">
    
    <h1>HOME</h1>

<p>Welcome this is the home page ..... more to come</p>    
</div>

<div class="mainCont">
<%=render 'layouts/categories'%>
</div>