config/routes.rb
Rails.application.routes.draw do
  
  resources :site_contents
  resources :categories
  resources :orders do 
    resources:orderitems
  end

  
  
  
  devise_for :users do 
    resources :orders 
  end
  
  get 'dynamicpage/:location' => 'static_pages#dynamicPage'
  
  
  post '/search' => 'items#search'
  get 'category/:title' => 'static_pages#category'
  
 # get 'cart/index'

  resources :items
  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'
  
  
  get '/login' => 'user#login'
  
    get '/logout' => 'user#logout'
    
    
    get '/checkout' => 'cart#createOrder' 
    
    
    # This looks like what we did for the add item ...... Muuhhhhh yes Liam you are right......
    
    
get '/remove/:id' => 'cart#remove'


get '/reduce/:id' => 'cart#reduce'


get '/cart/clearcart' => 'cart#clearcart'

get '/cart' => 'cart#index'

get '/cart/:id' => 'cart#add'

get '/upgrade/:id' => 'static_pages#upgrade'
get '/downgrade/:id' => 'static_pages#downgrade'

get '/allusers' => 'static_pages#allusers'


 get '/paid/:id' => 'static_pages#paid' 




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/site_content.rb
class SiteContent < ApplicationRecord
end

app/controllers/site_contents_controller.rb
class SiteContentsController < ApplicationController
  before_action :set_site_content, only: [:show, :edit, :update, :destroy]

  # GET /site_contents
  # GET /site_contents.json
  def index
    @site_contents = SiteContent.all
  end

  # GET /site_contents/1
  # GET /site_contents/1.json
  def show
  end

  # GET /site_contents/new
  def new
    @site_content = SiteContent.new
  end

  # GET /site_contents/1/edit
  def edit
  end

  # POST /site_contents
  # POST /site_contents.json
  def create
    @site_content = SiteContent.new(site_content_params)

    respond_to do |format|
      if @site_content.save
        format.html { redirect_to @site_content, notice: 'Site content was successfully created.' }
        format.json { render :show, status: :created, location: @site_content }
      else
        format.html { render :new }
        format.json { render json: @site_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_contents/1
  # PATCH/PUT /site_contents/1.json
  def update
    respond_to do |format|
      if @site_content.update(site_content_params)
        format.html { redirect_to @site_content, notice: 'Site content was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_content }
      else
        format.html { render :edit }
        format.json { render json: @site_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_contents/1
  # DELETE /site_contents/1.json
  def destroy
    @site_content.destroy
    respond_to do |format|
      format.html { redirect_to site_contents_url, notice: 'Site content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_content
      @site_content = SiteContent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_content_params
      params.require(:site_content).permit(:title, :heading1, :heading2, :location)
    end
end

app/helpers/site_contents_helper.rb
module SiteContentsHelper
end

app/views/site_contents/_form.html.erb
<%= form_for(site_content) do |f| %>
  <% if site_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site_content.errors.count, "error") %> prohibited this site_content from being saved:</h2>

      <ul>
      <% site_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :heading1 %>
    <%= f.text_field :heading1 %>
  </div>

  <div class="field">
    <%= f.label :heading2 %>
    <%= f.text_field :heading2 %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_contents/edit.html.erb
<h1>Editing Site Content</h1>

<%= render 'form', site_content: @site_content %>

<%= link_to 'Show', @site_content %> |
<%= link_to 'Back', site_contents_path %>

app/views/site_contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Site Contents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Heading1</th>
      <th>Heading2</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_contents.each do |site_content| %>
      <tr>
        <td><%= site_content.title %></td>
        <td><%= site_content.heading1 %></td>
        <td><%= site_content.heading2 %></td>
        <td><%= site_content.location %></td>
        <td><%= link_to 'Show', site_content %></td>
        <td><%= link_to 'Edit', edit_site_content_path(site_content) %></td>
        <td><%= link_to 'Destroy', site_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site Content', new_site_content_path %>

app/views/site_contents/new.html.erb
<h1>New Site Content</h1>

<%= render 'form', site_content: @site_content %>

<%= link_to 'Back', site_contents_path %>

app/views/site_contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @site_content.title %>
</p>

<p>
  <strong>Heading1:</strong>
  <%= @site_content.heading1 %>
</p>

<p>
  <strong>Heading2:</strong>
  <%= @site_content.heading2 %>
</p>

<p>
  <strong>Location:</strong>
  <%= @site_content.location %>
</p>

<%= link_to 'Edit', edit_site_content_path(@site_content) %> |
<%= link_to 'Back', site_contents_path %>