config/routes.rb
Rails.application.routes.draw do
  
  resources :site_contents
  resources :categories
  resources :orders do 
    resources:orderitems
  end

  
  
  
  devise_for :users do 
    resources :orders 
  end
  
  get 'dynamicpage/:location' => 'static_pages#dynamicPage'
  
  
  post '/search' => 'items#search'
  get 'category/:title' => 'static_pages#category'
  
 # get 'cart/index'

  resources :items
  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'
  
  
  get '/login' => 'user#login'
  
    get '/logout' => 'user#logout'
    
    
    get '/checkout' => 'cart#createOrder' 
    
    
    # This looks like what we did for the add item ...... Muuhhhhh yes Liam you are right......
    
    
get '/remove/:id' => 'cart#remove'


get '/reduce/:id' => 'cart#reduce'


get '/cart/clearcart' => 'cart#clearcart'

get '/cart' => 'cart#index'

get '/cart/:id' => 'cart#add'

get '/upgrade/:id' => 'static_pages#upgrade'
get '/downgrade/:id' => 'static_pages#downgrade'

get '/allusers' => 'static_pages#allusers'


 get '/paid/:id' => 'static_pages#paid' 




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    
    @orderitems = Orderitem.all
@orderitems = Orderitem.where(order_id: params[:id])

  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
  
  <h1>Items</h1>
     
      <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
        <p><%= item.description %></p>
       <p>Price <%= number_to_currency(item.price, :unit => "€") %>
       <br>
        Category: <%= item.category %>
        <br>
        Brand: <%= item.brand %></p>
       
       <p>
         <%= link_to 'Show',  item, :class => "button", :role => "button" %>
         
         <% if session[:login] == 1 %>
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
         <% end %>
         
         
         
         <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
       </p>
        
      </div>
    <% end %>
      
</div>

<br>
<% if user_signed_in? %>  
<%= link_to 'New Item', new_item_path, :class =>"button", :role=>"button" %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @items.length == 0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>


<table class="catalog">
       <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
        <p><%= item.description %></p>
       <p>Price <%= number_to_currency(item.price, :unit => "€") %>
       <br>
        Category: <%= item.category %>
        <br>
        Brand: <%= item.brand %></p>
       
       <p>
         <%= link_to 'Show',  item, :class => "button", :role => "button" %>
         
         <% if session[:login] == 1 %>
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
         <% end %>
         
         
         
         <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
       </p>
        
      </div>
    <% end %>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>



<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>